version: "3.7"

services:
  todo-app:
    container_name: app
    image: todo-app
    build:
      context: .
      target: build-base #airを使うためscratchではなく敢えてこちらを指定
      dockerfile: ./docker/default/go/Dockerfile
    command:
      - air
    volumes:
      - ./:/go/src/
    ports:
      - "8080:8080" #http
      - "2345:2345" # dlv