version: "3.7"

services:
  todo-app:
    container_name: app
    image: todo-app
    build:
      context: .
      target: run-base #buildして利用するtarget
      dockerfile: ./docker/default/go/Dockerfile
    ports:
      - "8080:8080" #http