version: "3.7"

services:
  graphql-app:
    container_name: graphql-app
    image: graphql-app
    build:
      context: .
      target: build-base #airを使うためscratchではなく敢えてこちらを指定
      dockerfile: docker/graphql/Dockerfile
    command:
      - air
    volumes:
      - ./:/go/src/
    ports:
      - "8080:8080" # http
      - "2345:2345" # dlv